haconiwa/haconiwa

mrblib/haconiwa.rb, mrblib/haconiwa/base.rb, mrblib/haconiwa/cli.rb, mrblib/haconiwa/runner.rb
After this, mruby haconiwa will have caught up to MRI haconiwa. So to be versioned as `0.1.0` !!
=> Re-implement haconiwa attach

.gitignore, .travis.yml, .travis_build_config.rb, README.md, Rakefile, bintest/haconiwa.rb, mrbgem.rake
=> Small refinements

mrbgem.rake, mrblib/haconiwa.rb, mrblib/haconiwa/base.rb, mrblib/haconiwa/cli.rb, mrblib/haconiwa/runner.rb, mrblib/haconiwa/version.rb, sample/sshd.haco, src/haconiwa.c
```console
$ sudo ./mruby/bin/haconiwa run sample/sshd.haco
Container successfullly up. PID={container: 7204, supervisor: 7203}
$ sudo ./mruby/bin/haconiwa kill sample/sshd.haco
Kill success
```
=> Support daemonize and kill

README.md, mrbgem.rake, mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, mrblib/haconiwa/version.rb, sample/nofile.haco, sample/nonpriv.haco
See examples.
```ruby
config.uid = "vagrant"
config.gid = "vagrant"
end
```
```ruby
config.resource.set_limit(:CPU,    10 * 60)
config.resource.set_limit(:NOFILE, 30)
end
```
=> Support rlimit and uid/gid(non-priv container)

README.md, mrbgem.rake, mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, mrblib/haconiwa/signal_handler.rb, mrblib/haconiwa/version.rb, sample/cpu.haco
Please see examples:
```console
$ sudo ./mruby/build/host/bin/haconiwa run sample/cpu.haco
Container successfullly up. PID={container: 13682, supervisor: 13681}
$ sudo kill -TTOU 13681
$ sudo kill -TTOU 13681
$ sudo kill -TTIN 13681
```
```console
$ sudo tail -f /tmp/sig_cpu-quota001.txt
Current cpu.cfs_quota_us = 40000
Changed cpu.cfs_quota_us = 50000
Current cpu.cfs_quota_us = 40000
...
```
=> Supervisor process now accepts some signals

.gitignore, Gemfile, Gemfile.lock, docker-compose.yml, packages/dockerfiles/Dockerfile.centos, packages/dockerfiles/Dockerfile.debian, packages/rpm/haconiwa.spec
```console
$ LANG=C sudo yum -q info haconiwa
Installed Packages
Name        : haconiwa
Arch        : x86_64
Epoch       : 1
Version     : 0.2.2
Release     : 1
Size        : 2.3 M
Repo        : installed
Summary     : MRuby on Container
URL         : https://github.com/haconiwa/haconiwa
License     : GPLv3+
Description : haconiwa - The MRuby on Container
```
=> Provide RPM package

mrbgem.rake, mrblib/vendor/uuid.rb
This will be useful for many case.
=> Add UUID and SecureUUID

.travis.yml
=> Make sudo=false

mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, sample/chroot.haco
=> Enter existing namespace on run

.gitignore, mrblib/haconiwa.rb, mrblib/haconiwa/cli.rb, mrblib/haconiwa/generator.rb, mrblib/haconiwa/provision.rb
=> The `haconiwa new` subcommand to create new haconiwa DSL template

.travis.yml, Rakefile, bintest/haconiwa.rb, bintest/walkthrough.rb, mrblib/haconiwa/generator.rb
This should be done by `root`...
Is this OK for travis?
=> Add bintest of haconiwa container tour

mrblib/haconiwa/cli.rb, mrblib/haconiwa/generator.rb
=> Implement haconiwa init --global

.travis.yml, bintest/walkthrough.rb, mrblib/haconiwa/process.rb
* Remove some errors and warnings...
=> Small fix about ps

mrblib/haconiwa/cli.rb, mrblib/haconiwa/process.rb
* Add `--no-header` option
* Friendly formatted
=> More useful ps command

mrblib/haconiwa/runner.rb
=> Fix...typo

mrblib/haconiwa/base.rb, mrblib/haconiwa/generator.rb, mrblib/haconiwa/provision.rb, mrblib/haconiwa/runner.rb
This follows behavior of ip netns
=> Add network etc sharing options, especially on provision

mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb
This is an ad hoc implementation, but some signal can be handled.
=> Run cleanup when supervisor is directly killed

mrblib/haconiwa/base.rb, mrblib/haconiwa/bootstrap.rb, mrblib/haconiwa/provision.rb, mrblib/haconiwa/runner.rb, sample/uid_mapping.haco
=> (A half way to) Unprivileged container

README.md, Rakefile, mrblib/haconiwa/version.rb, packages/deb/debian/changelog, packages/dockerfiles/Dockerfile.centos, packages/dockerfiles/Dockerfile.debian, packages/rpm/haconiwa.spec, packages/templates/changelog.yml
=> Push to fedora/{23,24}

mrbgem.rake, mrblib/haconiwa/base.rb, mrblib/haconiwa/logger.rb, mrblib/haconiwa/runner.rb
This is log example:
Debug log is also available, we can add this later in the future it will be needed.
=> Support logging via syslog

Rakefile, docker-compose.yml, mrbgem.rake, packages/dockerfiles/Dockerfile.centos, packages/dockerfiles/Dockerfile.centos6, packages/rpm/haconiwa.spec, packages/templates/Dockerfile.centos.erb, packages/templates/Dockerfile.centos6.erb, packages/templates/rpm-spec.erb
This is experimental haconiwa support dor CentOS 6
Kernels should be upgraded... I recommend.
=> Support CentOS 6 build

packages/dockerfiles/Dockerfile.centos, packages/dockerfiles/Dockerfile.centos6, packages/templates/Dockerfile.centos.erb, packages/templates/Dockerfile.centos6.erb
...Like a famous Japanese anime - 「もしかして」「私たち」
=> Fix inverted el6 and el7

README.md, mrblib/haconiwa/bootstrap.rb, mrblib/haconiwa/generator.rb
=> Add newborn bootstrap strategies

bintest/walkthrough.rb
Now lxc-create in CI sometimes occurs timeout.
So I want to change bootstrap strategy to newly added git clone in CI.
=> Change bootstrap strategy in CI walkthrough

mrblib/haconiwa/runner.rb
Unfortunately, `haconiwa run -t` is broken...
=> Fix broken attach option

mrblib/haconiwa/runner.rb
refs: FastContainer(JP) http://hb.matsumoto-r.jp/entry/2016/11/11/234915
=> CRIU-available container

mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb
This saves the parent process to do fork again! Maybe...
=> Replace fork & unshare to clone(2)

README.md, mrblib/haconiwa/base.rb, mrblib/haconiwa/generator.rb, mrblib/haconiwa/runner.rb, sample/sleeper001.haco
To get daemon's stderr and stdout!!!
=> Add DSL to open stdout/err for redirect

mrblib/haconiwa/runner.rb
=> Backport setns timing issue from #70

README.md, mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, sample/hooks.haco
=> Forwardport of hooks

mrblib/haconiwa/runner.rb
=> Guard to create existing cgroup

mrbgem.rake
=> Change repository used for build

.travis.yml, mrbgem.rake
* Skip mtest...
* Use patched (spec) version of mruby-onig
See: #82
=> Temporary fix of failing CI

mrblib/haconiwa/version.rb, packages/deb/debian/changelog, packages/dockerfiles/Dockerfile.centos, packages/dockerfiles/Dockerfile.centos6, packages/dockerfiles/Dockerfile.debian, packages/rpm/haconiwa.spec, packages/templates/changelog.yml
=> Release of 0.8.0

README.md, mrblib/haconiwa.rb, mrblib/haconiwa/base.rb, mrblib/haconiwa/cli.rb, mrblib/haconiwa/runner.rb, mrblib/haconiwa/wait_loop.rb, sample/reload.haco
```ruby
config.support_reload :cgroup
config.cgroup["foo"] = rand(1024).to_s
end
```
Then, cgroup value `"foo"` can be reloaded and define its value in each evaluated context.
=> Support `haconiwa reload`

.travis.yml, README.md, bintest/fixtures/reload-test.haco, bintest/reload.rb, build_config.rb, mrbgem.rake, mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, mrblib/haconiwa/wait_loop.rb, sample/reload.haco
To check DSL, see example
Now it works:
```console
vagrant@localhost:haconiwa$ sudo prlimit -n -p 2513                                                            
RESOURCE DESCRIPTION              SOFT  HARD UNITS
NOFILE   max number of open files 4096 65536 
vagrant@localhost:haconiwa$ sudo ./mruby/bin/haconiwa reload sample/reload.haco
Reload success
vagrant@localhost:haconiwa$ sudo prlimit -n -p 2513
RESOURCE DESCRIPTION              SOFT  HARD UNITS
NOFILE   max number of open files 2048 65536 
```
=> Support resouce limit reloading

bintest/walkthrough.rb, mrblib/haconiwa/wait_loop.rb
After this, haconiwa can log thread exceptions. This is one small step for threaded haconiwa...
=> Implement watchdog thread

mrblib/haconiwa/wait_loop.rb
=> Small fixes on messages

mrbgem.rake, test/runner.rb
* tests around mruby-tempfile are failing on my environment... and mruby-tempfile has warnings.
=> Reduce deps on test

README.md, mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, sample/hooks.haco, sample/multi.haco
See updated README for details.
=> Add new hooks

.github/CONTRIBUTING.md, README.md
We do Loose-tie policy!
Including 日本語でのプルリクやイシュー作成について .
=> Add CONTRIBUTING.md for organizations

README.md, mrbgem.rake, mrblib/haconiwa/provision.rb, mrblib/haconiwa/runner.rb, sample/process.rb
Old mruby-mount has some GC trouble.
So upgraded and use new module function API.
=> Bump mruby-mount version and use new API

Makefile, Rakefile
Packages should not be stripped
=> Skip strip process for debug

README.md, mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, mrblib/haconiwa/wait_loop.rb
Wait loop's interval is now customizable.
```ruby
#...
config.wait_interbal = 500 # in ms
end
```
Then run wait() i every 500 ms. (I set default to in every 50 ms)
=> Support waitloop interval

mrblib/haconiwa/wait_loop.rb
Timers got duplicated signals...
=> Fix that cannot define timers in count >= 2

README.md, mrblib/haconiwa/base.rb, test/dsl_test.rb
=> Support container in-memory metadata

Rakefile, docker-compose.yml, packages/deb/debian/control.9, packages/dockerfiles/Dockerfile.debian9, packages/templates/Dockerfile.debian.erb, packages/templates/Dockerfile.debian9.erb
Add control, Dockerfile and tasks
Fix: #120 maybe!!
=> Support debian 9

Rakefile, bintest/fixtures/hooks-test.haco, bintest/fixtures/reload-test.haco, bintest/parallel.rb, bintest/walkthrough.rb, mrbgem.rake
Haconiwa cannot be built on even my box now... Then temporally fix.
=> Catching up current environment

.travis.yml, Gemfile.lock
=> The bundle update

mrblib/haconiwa/runner.rb
hi Ucchi!!
I Added processing to delete the pid file at the end of the container.
=> Delete the pid file at the end of the container

bintest/fixtures/just-sleep.haco.erb, bintest/pidfile.rb, bintest/walkthrough.rb, mrblib/haconiwa/runner.rb
=> Add a test case for removing pidfiles

mrblib/haconiwa/base.rb
=> Allow to write: add_mount_point '...', data: 'data'

build_config.rb, mrbgem.rake, mrblib/haconiwa/base.rb, mrblib/haconiwa/criu_service.rb, mrblib/haconiwa/runner.rb, sample/criu-rails.haco, sample/criu.haco, sample/just_a_chroot.haco
=> Implement checkpoint in the least config

mrblib/haconiwa/criu_service.rb, sample/criu-rails.haco, sample/criu.haco
=> Re-assign IP when container is restored

mrblib/haconiwa.rb, mrblib/haconiwa/action_script.rb, mrblib/haconiwa/base.rb, mrblib/haconiwa/criu_service.rb, mrblib/haconiwa/runner.rb, sample/criu-rails.haco, sample/criu.haco
=> Restore a container with newly assigned IP

mrblib/haconiwa.rb, mrblib/haconiwa/base.rb, mrblib/haconiwa/cli.rb, mrblib/haconiwa/criu_service.rb, mrblib/haconiwa/network_handler.rb, mrblib/haconiwa/runner.rb, mrblib/haconiwa/util.rb, sample/criu-rails.haco
=> Enable hook on restored process

mrblib/haconiwa/action_script.rb, mrblib/haconiwa/base.rb, mrblib/haconiwa/criu_service.rb, sample/criu-rails.haco
NOTE: This `restore` requires an image to be restored with `--external mnt[]:`
=> Restores external bind mount points

mrbgem.rake
=> Includes haconiwa itself's revision

mrblib/haconiwa/base.rb, mrblib/haconiwa/criu_service.rb, sample/criu-rails.haco
=> Support rename of customized cgroup controllers on restore

mrblib/haconiwa/base.rb, mrblib/haconiwa/criu_service.rb, sample/criu-rails.haco
* activate log_level
* enable file logging on restore
=> More support for criu's log options

Rakefile, mrbgem.rake, packages/dockerfiles/Dockerfile.centos, packages/dockerfiles/Dockerfile.debian, packages/dockerfiles/Dockerfile.debian9, packages/templates/Dockerfile.centos.erb, packages/templates/Dockerfile.debian.erb, packages/templates/Dockerfile.debian9.erb
=> Drop my fork dep

mrbgem.rake
=> Check current checked-out mruby's revision to change bundled hashes

mrblib/haconiwa/base.rb, sample/criu.haco
See sample: https://github.com/haconiwa/haconiwa/pull/176/files#diff-eeefd962a394a54b498fd089bac239f6R38
=> Dynamic branching to run in restore/normal mode

mrblib/haconiwa/base.rb, mrblib/haconiwa/logger.rb
Hi ukkun!
I'm having trouble with the flow of the haconiwa log.
What do you think about this kind of implementation?
cc: @k1Low
=> I want to reduce syslog

mrblib/haconiwa/action_script.rb, mrblib/haconiwa/criu_service.rb
We got some troubles in restoring network. Fixed what I found.
=> Fix network restore issues

mrblib/haconiwa/base.rb, mrblib/haconiwa/criu_service.rb
This may be required to restore MySQL-connected apps (e.g. Rails) ?
=> Support tcp-established option

Gemfile, Gemfile.lock, Rakefile, mrblib/haconiwa/version.rb, packages/deb/debian/changelog, packages/dockerfiles/Dockerfile.bionic, packages/dockerfiles/Dockerfile.centos, packages/dockerfiles/Dockerfile.debian, packages/dockerfiles/Dockerfile.debian9, packages/rpm/haconiwa.spec, packages/templates/changelog.yml
This is a super long-awaited feature!!!
=> Add a changelog writer task

.travis.yml
=> Change travis base container to xenial

mrbgem.rake
Change ruby-onig-regexp to upstream
=> change mruby-onig-regexp repository

sample/criu.haco, sample/test_acrion.sh
The log is like:
```
Sep 24 08:55:20 ubuntu-bionic haconiwa.action-script[6705]: Hello!
Sep 24 08:55:20 ubuntu-bionic haconiwa.action-script[6706]: CRTOOLS_SCRIPT_ACTION: post-resume                                                             
Sep 24 08:55:20 ubuntu-bionic haconiwa.action-script[6707]: CRTOOLS_IMAGE_DIR: /proc/6603/fd/1048574                                                       
Sep 24 08:55:20 ubuntu-bionic haconiwa.action-script[6708]: CRTOOLS_INIT_PID: 6612                                                                         
```
=> Update action sample

mrblib/haconiwa/network_handler.rb
Hi ucchi!
i want to skip to make netns if aleady exist netns.
in my case, `ip netns add` is very slow that's why i want to create netns before container create.
=> skip make netns if aleady exist

mrblib/haconiwa/base.rb, mrblib/haconiwa/wait_loop.rb, sample/criu.haco
This is alpha feature... Add support for port readiness hook.
This is useful to make CRIU image (maybe...)
=> Support readiness hook

mrblib/haconiwa/base.rb, mrblib/haconiwa/network_handler.rb
Hi ucchi!
Deleting netns is a very heavy process. Sometimes I want to avoid it.
=> I don't want to erase netns

mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, sample/criu-rails.haco, src/haconiwa.c
This may be a bottleneck when the host filesystem has complex mountpoints!
=> Add skip_make_rslave_on_host_root option for fast startup

mrblib/haconiwa/base.rb
refs: https://github.com/pyama86/mruby-ifaddr/pull/1
=> add subnet in response from mruby-ifaddr

Rakefile, hack/eval_patch.patch
This patch is from https://github.com/mruby/mruby/pull/4834 and modified for mruby 2.0.1
=> The patching to avoid eval segv

mrbgem.rake, mrblib/haconiwa/base.rb, mrblib/haconiwa/runner.rb, sample/criu.haco
This is useful to work with PSI!!!
=> Enable to just assign containers to v2 group without limitation

mrblib/haconiwa/runner.rb
=> Delete v2 group on terminate
