haconiwa/haconiwa

- .gitignore
- Rakefile
- mrbgem.rake
- mrblib/haconiwa.rb
- mrblib/haconiwa/cli.rb
- src/haconiwa.c
This is perfect for debug!
```console
$ ./mruby/bin/haconiwa revisions
mgem and mruby revisions:
--------
MRUBY_CORE_REVISION     22464fe5a0a10f2b077eaba109ce1e912e4a77de
mruby-argtable          d0077ef2504be4cb3ae8e855dfe88a532fb6997b
mruby-capability        ba12370b02abd696eeede4c3413a0aa948c7af17
mruby-cgroup            489058afba3dfae450513ea1d40c8e0bb007fee6
mruby-dir               0c3c538855dd15208d34fee96b13675e564bb4b6
mruby-exec              f70bbf735f8370729dcb2cab019d593c4a5d5617
mruby-io                93d481d4b49829e37b1f501c7307663c6327dfab
mruby-mount             dabaa7c487e09a878893d06573500e851cb20364
mruby-namespace         f5dbc47b3174a117e26d5ff6e21c1322a650e45f
mruby-process           e532ff8837ebed35bdc03f26aed6a9105bbd7c44
mruby-procutil …
```
> Show mgem/mruby revisions on compile

- LICENSE_argtable3
- README.md
- mrbgem.rake
Current status:
```console
$ ls -lh ./mruby/build/x86_64-pc-linux-gnu/bin/haconiwa 
-rwxr-xr-x 1 vagrant vagrant 748K  7月 13  2016 ./mruby/build/x86_64-pc-linux-gnu/bin/haconiwa
$ ldd ./mruby/build/x86_64-pc-linux-gnu/bin/haconiwa                                                                                                                          
linux-vdso.so.1 =>  (0x00007fff15efc000)
libm.so.6 => /lib64/libm.so.6 (0x00007f2d46a3d000)
libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f2d467f7000)
libncurses.so.5 => /lib64/libncurses.so.5 (0x00007f2d465cf000)
libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f2d463a5000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2d46189000)
librt.so.1 => /lib64/librt.so.1 (0x00007f2d45f80000)
libcap.so.2 => /lib64/libcap.so.2 …
```
> Use static link argtable3

- Rakefile
- build_config.rb
- mrbgem.rake
Current status:
```console
$ ldd `which haconiwa`
linux-vdso.so.1 =>  (0x00007ffd66bdd000)
libm.so.6 => /lib64/libm.so.6 (0x00007fecf2fea000)
libreadline.so.6 => /lib64/libreadline.so.6 (0x00007fecf2da4000)
libncurses.so.5 => /lib64/libncurses.so.5 (0x00007fecf2b7c000)
libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007fecf2952000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fecf2736000)
librt.so.1 => /lib64/librt.so.1 (0x00007fecf252d000)
libcap.so.2 => /lib64/libcap.so.2 (0x00007fecf2328000)
libc.so.6 => /lib64/libc.so.6 (0x00007fecf1f66000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007fecf1d61000)
/lib64/ld-linux-x86-64.so.2 (0x00007fecf32f6000)
libattr.so.1 => /lib64/libattr.so.1 (0x00007fecf1b5c000)
```
> Lessen dependent dynamic-linked libraries

- README.md
`haconiwa run` with example haco file failed with following error message.
```
TypeError: non float value
RuntimeError: Invalid or unsupported controller name: pid
```
> Fixed example haco file

- README.md
- mrblib/haconiwa.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/bootstrap.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/provision.rb
- mrblib/haconiwa/version.rb
- mrblib/vendor/minipathname.rb
- mrblib/vendor/run_cmd.rb
- sample/chroot.haco
- sample/debootstrap.haco
```ruby
config.bootstrap do |b|
b.project_name = "chroot-boot001"
b.strategy = "lxc"
b.os_type = "alpine"
end
config.provision do |p|
p.run_shell <<-SHELL
export DEBIAN_FRONTEND=nonintaractive
export LANG=C
apt-get -y update
apt-get -y install git openssh-server
sed -i 's/Port.*/Port 2222/' etc/ssh/sshd_config
SHELL
p.run_shell <<-SHELL, name: "setup-user"
export DEBIAN_FRONTEND=nonintaractive
export LANG=C
adduser haconiwa-op --disabled-password --gecos "" || true
echo 'haconiwa-op:haconiwa' | chpasswd
SHELL
end
end
```
`bootstrap` supports lxc, debootstrap (docker soon...?)
`provision` ... supports shell, or ansible looks good? (chef/itamae ... I have no idea bridging ruby and mruby)
> Implement create subcommand(bootstrap and provisioning)

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/generator.rb
- mrblib/haconiwa/runner.rb
- sample/chroot.haco
* Deprecate `mount_independent_procfs`
* Add some internal mounter, following [OCI spec](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#default-filesystems)
> Container dependent filesystems

- README.md
- mrbgem.rake
- mrblib/haconiwa.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/global_config.rb
- mrblib/haconiwa/process.rb
- mrblib/haconiwa/runner.rb
The future:
```console
$ haconiwa ps
NAME        COMMAND       CREATED_AT                   STATUS  META
haconiwa001 /sbin/init    Mon Aug 22 15:00:01 JST 2016 running foo=bar
haconiwa002 /sbin/sshd -D Mon Aug 22 15:30:46 JST 2016 running foo=buz
```
* If file `/etc/haconiwa.conf.rb` exists, then the global config is available.
* If etcd is available, Haconiwa registers container's informations to etcd. `haconiwa ps` just use this.
> Implement `haconiwa ps`

- bintest/walkthrough.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/runner.rb
```bash
haconiwa run foo.haco -- /bin/sleep 100
```
Ignored unintendedly, so fixed
> Override init_command from command line arguments

- mrbgem.rake
`ENV['FOOBAR']` available and you can pass:
```bash
NONETNS=1 haconiwa run sample.haco
```
> Support ENV object in DSL

- build_config.rb
- mrbgem.rake
- mrblib/haconiwa.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/watch.rb
- mrblib/vendor/uuid.rb
- sample/sleeper001.haco
- sample/watch-sample.rb
Prepare small container template:
```ruby
suffix = UUID.secure_uuid("%x%x")
config.name = "haconiwa-#{suffix}"
config.init_command = ["/bin/sleep", UUID.secure_random(30..60).to_s]
config.daemonize!
root = Pathname.new("/var/lib/haconiwa/common")
config.chroot_to root
#...
end
```
Prepare watch.rb file:
```ruby
Haconiwa.watch do |config|
config.watch :cluster do |event|
if event.cluster.count < 5
Haconiwa.spawn "/etc/haconiwa/haco.d/test001.haco"
end
end
end
```
Run:
```console
$ haconiwa watch watch.rb
...
```
Then container count will be kept to 5, replacing container processes:
```console
$ haconiwa ps
NAME                    HOST                    ROOTFS                          COMMAND                 CREATED_AT                      STATUS          PID …
```
> Implement `haconiwa watch`

- mrblib/haconiwa/runner.rb
Close a remaining pipe in supervisor process:
```
[vagrant@udzura haconiwa]$ sudo haconiwa run /etc/haconiwa/haco.d/test001.haco
Container successfully up. PID={container: 16413, supervisor: 16412}
[vagrant@udzura haconiwa]$ sudo ls -l /proc/16412/fd
合計 0
lr-x------ 1 root root 64  8月 30 12:24 0 -> /dev/null
l-wx------ 1 root root 64  8月 30 12:24 1 -> /dev/null
l-wx------ 1 root root 64  8月 30 12:24 2 -> /dev/null
lrwx------ 1 root root 64  8月 30 12:24 3 -> socket:[437006]
lrwx------ 1 root root 64  8月 30 12:24 4 -> socket:[437007]
lrwx------ 1 root root 64  8月 30 12:24 5 -> socket:[437008]
lrwx------ 1 root root 64  8月 30 12:24 6 -> socket:[437015]
lrwx------ 1 root root 64  8月 30 12:24 7 -> socket:[437016]
lrwx------ 1 root root 64  8月 30 12:24 8 -> socket:[437017]
lr-x------ 1 root …
```
> Fix a FD leak

- LICENSE_libuv
- packages/deb/debian/copyright
- packages/templates/rpm-spec.erb
Haconiwa is now bundling static linked libuv
> Add libuv license files a d docs

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/uid_mapping.haco
Add:
```ruby
config.namespace.set_uid_mapping min: 0, max: 10_000, offset: 100_000
config.namespace.set_gid_mapping min: 0, max: 10_000, offset: 100_000
```
Then new user namespace is spawned.
```
...
root      6404  0.2  0.4  17008  4384 pts/0    S    03:28   0:00  |                       \_ ./haconiwa run hoge2.haco
100000    6405  0.0  0.0   1524   936 pts/0    S+   03:28   0:00  |                           \_ /bin/sh
```
(NOTE: I ensured this works only on Ubuntu Xenial now...)
> Support uid/gid mapping

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/bootstrap.rb
- mrblib/haconiwa/cli.rb
Add a pstprocess hook. e.g.:
```ruby
config.bootstrap do |b|
b.strategy = "tarball"
b.archive_path = "/usr/local/src/testball.tar.xz"
b.tar_options = ["-v"]
b.postprocess :shell, <<-SHELL
mknod -m 444 #{root}/dev/random c 1 9
mknod -m 444 #{root}/dev/urandom c 1 9
SHELL
end
```
And, I've added `haconiwa run --bootstrap` to boot on run
> Bootstrap hooks

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/sleeper001.haco
* Invoke `apply_capability` just before exec'ing (after unshare and switch g/uids)
* According to [man 7 user_namespace](http://man7.org/linux/man-pages/man7/user_namespaces.7.html), splitting user namespace also splits user capabilities. So it is more desirable to set caps just after g/uid switching
* Fixed error messages
> Dropping caps just before on exec

- mrbgem.rake
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/runner.rb
* Small refacrtor: split uid/gid config model
* `attach` supports `-u/--uid` and `-g/--gid`. If these are specified, DSL's uid/gid will be ignored.
> [WIP]Set uid/gid properly on attach

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
Reverts haconiwa/haconiwa#56
Direct use of `clone(2)` seems more dangerous than I had expected, so keep this patch to `use-clone` branch and revert it in master.
> Revert "Replace fork & unshare to clone(2)"

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
See: http://karelzak.blogspot.jp/2015/04/persistent-namespaces.html
```
mount --bind /root/mntns /root/mntns
mount --make-rprivate /root/mntns
```
Then
```ruby
config.namespace.unshare "mount", persist_in: "/root/mntns/mount.test"
```
After all, mount namespae is persisted and can be reentered.
> Persistent namespace

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/generator.rb
- sample/drop_cap_sys_time.haco
If you set no capability config, new process has these caps:
```console
bash-4.3# getpcaps $$
Capabilities for `1': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_setgid,cap_setuid,cap_setpcap,cap_net_raw,cap_setfcap+ep
```
Explicit `reset_to_privileged!` declaration reset caps to blank, then we can customize caps as we want.
> Introduce default capabilities by whitelist

- README.md
- mrbgem.rake
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- mrblib/haconiwa/signal_handler.rb
- mrblib/haconiwa/wait_loop.rb
- sample/timer.haco
e.g. terminate container by elapsed time:
```ruby
config.after_spawn(msec: 10 * 60 * 1000) do |base|
::Process.kill :TERM, base.pid
end
```
Also, signal handlers are moved to `UV::Signal` based ones.
> Add timer hook(config.after_spawn)

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/chroot.haco
Supported:
* init's working dir: `config.workdir`
* resolves mount target src dir from cwd
> Refine cwd handling

- .travis.yml
- bintest/walkthrough.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/bootstrap.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/provision.rb
- mrblib/haconiwa/runner.rb
- mrblib/haconiwa/wait_loop.rb
- sample/multi.haco
- sample/sleeper001.haco
The example says itself:
```ruby
config.daemonize!
root = Pathname.new("/var/lib/haconiwa/8cfccb3d")
config.chroot_to root
3.times do |i|
config.define do |c|
suffix = UUID.secure_uuid("%x%x")
c.name = "haconiwa-#{suffix}"
c.init_command = ["/bin/sleep", (30 + i*10).to_s]
c.command.set_stdout(file: "/tmp/test-#{suffix}.stdout")
c.command.set_stderr(file: "/tmp/test-#{suffix}.stderr")
end
end
end
```
This implementation may have many bugs, so this is just a small step.
> [WIP]First implementation of multi-container ready haconiwa

- mrbgem.rake
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/cgroup.haco
This PR enable Haconiwa to access and control resources via [cgroup-v2](https://www.kernel.org/doc/Documentation/cgroup-v2.txt) filesystem.
My image of DSL spec:
```ruby
config.cgroup do |cgroup|
cgroup["pids.max"] = 1024
end
config.cgroup :v2 do |cgroup|
cgroup["io.max"] = "8:0 rbps=1048576 wbps=1048576"
end
#...
```
> Support cgroupv2

- mrblib/haconiwa/runner.rb
hi!
Fixed as netns did not work when attach command haconiwa
Always next to you!!
> Uid is required to switch netns

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/hooks.haco
This patch is making Haconiwa more programmable container framework. This adds hooks:
* before_fork
* after_fork(in child)
* before_chroot(in child)
* after_chroot(in child. This is the last timing before `exec`)
* before_start_wait
* teardown
* More hooks to be required
* Good name(general... what is general)
* ~~Because PID namespace is jailed, we cannot call `fork` on some hook(especially on teardown), this means functions like `Kernel#system` are unavailable at these timing. This will be fixed by using `Namespace.clone` instead of `Process.fork`, which looks unstable...~~
> General hooks in container spawning process 

- build_config.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/exception.rb
- mrblib/haconiwa/logger.rb
- mrblib/haconiwa/runner.rb
This patch includes Ruby-level exception logger. See #72 :)
I tried in real binary:
```
Jan 30 06:42:39 udzura haconiwa.haconiwa-1b8fb27[2044]: Base setting DSL is evaluated
Jan 30 06:42:39 udzura haconiwa.haconiwa-1b8fb27[2044]: pids: 2046
Jan 30 06:42:39 udzura haconiwa.haconiwa-1b8fb27[2044]: Container cluster successfully up. PID={supervisors: [2046], root: 2045}
Jan 30 06:42:39 udzura haconiwa.haconiwa-1b8fb27[1]: Container is going to exec: ["/bin/bass"]
Jan 30 06:42:39 udzura haconiwa.haconiwa-1b8fb27[1]: execve failed
Jan 30 06:42:39 udzura haconiwa.haconiwa-1b8fb27[1]: An exception is occurred when spawning haconiwa:
Jan 30 06:42:39 udzura haconiwa.haconiwa-1b8fb27[1]: /Users/udzura/.ghq/github.com/haconiwa/haconiwa/mrblib/haconiwa/logger.rb:21: execve failed …
```
> Forwardport of detailed syslog logger

- .travis.yml
- mruby-uv test failed when disabled ipv6 loopback 
- clang path was not found when using sudo
> Fix mruby-uv segfault of mtest on Travis CI

- .gitignore
- mrbgem.rake
In recent releases hacofiles using cgroup emit warnings (fortunately cgroup itself seems working fine).
```console
$ sudo haconiwa run test.haco 
Error: failed to set /sys/fs/cgroup/cpuset/haconiwa-5eb974c9/cpuset.memory_pressure: Invalid argument
Error: failed to set /sys/fs/cgroup/cpuset/haconiwa-5eb974c9/cpuset.effective_cpus: Invalid argument
Error: failed to set /sys/fs/cgroup/cpuset/haconiwa-5eb974c9/cpuset.effective_mems: Invalid argument
Container fork success and going to wait: pid=1752
root@haconiwa-5eb974c9:/# exit
exit
Container(1752) finish detected: #<Process::Status: pid=1752,exited(0)>
Container successfully exited: #<Process::Status: pid=1752,exited(0)>
```
I have tried mruby-cgroup's version reverted locally, then these warnings are erased.
I want to get this warnings …
> Use fixed version of mruby-cgroup

- mrblib/haconiwa/runner.rb
When you use haconiwa as advanced chroot tool, there is unexpected side-effect...
> Do not update hostname when UTS namespace not activated

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
This means you can even skip chroot'ing. Invoke processes only for namespace or cgroup, &c ;)
> Skip chroot if no definition of chroot_to

- mrbgem.rake
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
Added parent's PID file, and then use this file to wait.
> Ensure `kill` waits until the super-supervisor process exits

- mrbgem.rake
Since https://github.com/mattn/mruby-thread/pull/47 is merged.
> Point mruby-thread to mgem again

- mrbgem.rake
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/seccomp.haco
DSL spec:
```ruby
config.seccomp.filter(default: :allow) do |rule|
rule.kill(:chroot)
end
config.capabilities.allow 'cap_sys_chroot'
```
Then, you cannot invoke `chroot(2)` even if you have capabilities.
(This may be available in CentOS 7 (kernel 3.10) / Ubuntu xenial (kernel 4.4) ...)
> Support seccomp filter DSL

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/logger.rb
- mrblib/haconiwa/runner.rb
- sample/sshd.haco
* Set container's euid to haconiwa supervisor's ruid
* Validate the ruid to run haconiwa
* Return euid to ruid when containers have been spawned
> Making proper behavior when haconiwa binary is set-user-id root'ed

- mrbgem.rake
Current `iij/mruby-syslog` has some oldish codes. So I have done the rewrite.
> Use newly rewritten version of mruby-syslog

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/runner.rb
- mrblib/vendor/expand_path.rb
Current `File.expand_path` implementation in mruby (IOW nested methode definition in mruby) seems to be behaving suspiciously. Especially, segfaults on GC occurred around these function calls.
So I just rewrite the implementation using a naive private method.
(And added some log refinements)
> Avoid File.expand_path

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
We now can mock /proc/cpuinfo, /proc/meminfo... to container's environment, not hosts one.
> Support usage of lxcfs in haconiwa container

- README.md
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/network_handler.rb
- mrblib/haconiwa/runner.rb
- sample/network.haco
See sample.
```console
$ sudo haconiwa init --bridge --bridge-name=haconiwa0 --bridge-ip=10.127.127.1/24
```
```ruby
config.network.namespace = config.name
config.network.container_ip = '10.127.127.10'
config.network.bridge_name = 'haconiwa0'
#...
end
```
> Enable basis of netowrking config

- tools/haconiwa/haconiwa.c
Because euid/egid would not be inherited after `execve(2)`ed.
> Change the process's real guid

- .travis.yml
- mrblib/haconiwa/version.rb
After checkpoint-restore support, Haconiwa will be verison 1.0.0
> Version to 1.0.0.alpha

- mrbgem.rake
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/wait_loop.rb
- sample/cgroup_event.haco
Now wa can use this kind of hooks:
```ruby
haconiwa = Haconiwa.define do |config|
config.cgroup["memory.limit_in_bytes"] = 16 * 1024 * 1024
config.add_cgroup_hook type: "memory_pressure", level: level do |base|
Haconiwa::Logger.puts "[#{base.pid}] Memory pressure now!"
system "ps auxf | grep -e RSS -e GC.disable"
::Process.kill :TERM, base.pid
end
end
```
Example run:
```console
$ sudo env PRESSURE_LEVEL=critical ./mruby/bin/haconiwa run sample/cgroup_event.haco -T                           
Memory pressure level: critical
Create lock: #<Lockfile path=/var/lock/.cgroup-event-test.hacolock>
Container fork success and going to wait: pid=6050
Cgroup hook[memory_pressure] starting...
[6050] Memory pressure now!
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root …
```
> Basic implementation of cgroup hook: memory_pressure

- mrblib/haconiwa/base.rb
I think that it is unnecessary to make it as strict as the web server can not be started with default. Therefore, it gives network capability.
> Add net_bind_service to allowed capabilities

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/criu_service.rb
It is useful to handle crius installed other than `"/usr/local/sbin/criu"`
> Set criu's location as config

- bintest/fixtures/hooks-test.haco
- bintest/fixtures/just-sleep.haco.erb
- bintest/fixtures/reload-test.haco
- bintest/walkthrough.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/criu_service.rb
- mrblib/haconiwa/runner.rb
- mrblib/haconiwa/wait_loop.rb
- sample/criu-rails.haco
- src/haconiwa.c
* Restore mount namespace via CRIU
* Use pivot_root instead of chroot. To force using chroot, write below:
```ruby
config.filesystem.use_legacy_chroot = true
```
> Restore mount namespace / use pivot_root to change rootfs

- mrbgem.rake
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/apparmor.haco
- sample/apparmor_profile/haconiwa-deny-top-command
Added restriction by AppArmor profile to haconiwa container.
```bash
$ cat /etc/apparmor.d/haconiwa/haconiwa-deny-top-command
#include <tunables/global>
profile haconiwa-deny-top-command flags=(attach_disconnected,mediate_deleted) {
#include <abstractions/base>
file,
deny /usr/bin/top mrwklx,
deny @{PROC}/sysrq-trigger rwklx,
}
$ sudo apparmor_parser -r -W /etc/apparmor.d/haconiwa/haconiwa-deny-top-command
$ sudo ./mruby/build/host/bin/haconiwa start ./sample/apparmor.haco
Create lock: #<Lockfile path=/var/lock/.haconiwa-apparmor-test.hacolock>
Container fork success and going to wait: pid=2228
root@haconiwa-apparmor-test:/# top
bash: /usr/bin/top: Permission denied
root@haconiwa-apparmor-test:/# echo c > /proc/sysrq-trigger
bash: /proc/sysrq-trigger: Permission denied
```
Anothor …
> Support AppArmor

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
- sample/criu.haco
* To create container's PID=1 stdout/.err logging in the container itself, use `file:`, using path from  container's root
* To create this in the container's host, use `host_file:`.
> Set stdout/stderr file in both host and pivoted root

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/criu_service.rb
- sample/criu-rails.haco
We use '`--external mnt[]:` to automatically detect external bind mounts, but in some case it fails, especially when we use NFS and bind-mount it.
These options are to fight against this kind of use case.
> Support external bind mount, which are not auto-detected

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
```ruby
config.filesystem.masked_paths = [
"/dev/foo",
"/proc/bar",
...
]
```
Then these paths are masked in a container
> Implement masked paths

- mrblib/haconiwa/00_hookable.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/criu_service.rb
- mrblib/haconiwa/runner.rb
- sample/criu-rails.haco
Please see example:
```ruby
config.add_general_hook :before_restore do |base|
Haconiwa::Logger.info "Now in :before_restore!"
end
config.add_general_hook :after_restore do |base|
Haconiwa::Logger.info "Now in :after_restore! PID=#{base.pid}"
end
```
```
Oct  4 09:26:42 foo haconiwa.chroot-rails001-[28408]: Now in :before_restore!                                                                     
Oct  4 09:26:42 foo haconiwa.chroot-rails001-[28408]: Going to exec: ["/usr/local/sbin/criu", "restore",... ]
...
Oct  4 09:26:43 foo haconiwa.chroot-rails001-[28408]: Now in exec'ed haconiwa supervisor process
Oct  4 09:26:43 foo haconiwa.chroot-rails001-[28408]: Now in :after_restore! PID=28413
Oct  4 09:26:43 foo haconiwa.chroot-rails001-[28408]: WaitLoop instance status: …
```
> Implement before and after restore hooks

- mrblib/haconiwa/criu_service.rb
This is useful when you failed to exec restored process...
> Making pid intermediate file name unique

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/cli.rb
- mrblib/haconiwa/criu_service.rb
- mrblib/haconiwa/runner.rb
- mrblib/haconiwa/util.rb
- sample/criu-rails.haco
This allows users to dump running containers.
```console
$ sudo ./mruby/bin/haconiwa checkpoint --help
-R, --running             Create checkpoint of running container. Detect container's PID via hacofile(in case without --target)
-t, --target=PID          Container's *root* PID to make checkpoint. This implies --running
-h, --help                Show help
HACO_FILE                 Put the config file at the end of command
```
> Implement checkpoint--running/--target=PID option

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/criu_service.rb
Ref: https://criu.org/External_bind_mounts
Path to be specified in `--external` should not be Host path.
> Use chrooted_dest instead as mnt[*]'s key

- mrblib/haconiwa/base.rb
If some settings are overridden in `config.define` block, these are ignored on a newly restored container.
> Pass the first base instance to CRIURestoredRunner

- mrblib/haconiwa/base.rb
- For logs, use `O_WRONLY` and `O_APPEND`. `a` fits this.
- This is MUST to restore log fds via CRIU
> Do not set `+`, this implies `O_RDWR`.

- mrblib/haconiwa/action_script.rb
- mrblib/haconiwa/base.rb
- mrblib/haconiwa/logger.rb
- sample/criu.haco
- test/logger_test.rb
`Haconiwa::Logger.*` cannot be called in condition where `Haconiwa::Base` is not set up.
This is unuseful in some case (action script, top-level Hacofile logging). So I rewrite logging code in singleton pattern and lazy initialization.
> Refactor logger

- mrblib/haconiwa/action_script.rb
If run the iproute2 scripts on `post-setup-namespaces`, this inhivits already listened sockets to be restored.
`post-resume` may work...
> Run the action script of resetting IP after fds are restored

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/version.rb
- packages/deb/debian/changelog
- packages/dockerfiles/Dockerfile.bionic
- packages/dockerfiles/Dockerfile.centos
- packages/dockerfiles/Dockerfile.debian
- packages/dockerfiles/Dockerfile.debian9
- packages/rpm/haconiwa.spec
- packages/templates/changelog.yml
This enable haconiwa to run:
```
$ haconiwa checkpoint --running
$ haconiwa restore
```
NOTE that checkpoint without running container is still alpha version.
> Release 0.10.0

- mrblib/haconiwa/00_hookable.rb
- mrblib/haconiwa/runner.rb
This hook is invoked:
* just after container(inside) network is available, before any unshare
* invoked in container-to-be process
> Add after-network_initialized hook to control networks

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
`config.name` で設定された値はhostnameとcgroup名に利用されていますが、これらを別々に設定したいです。
cgroup_nameを別に設定できるように機能追加しています
```
config.cgroup_name = "foobar"
```
> configure cgroup name and hostname individually

- Makefile
Make haconiwa binary installable to any path.
Default installation path is `$(CURDIR)/debian/$(package)/usr` .
If want to change the installation location, specify `PREFIX` at `make install` .
> Change install prefix

- bintest/fixtures/hooks-test.haco
- bintest/hooks.rb
- mrblib/haconiwa/wait_loop.rb
According to [this change](https://github.com/udzura/mruby-fibered_worker/pull/10/files#diff-a6bd15363d22bd629088cdb36fb599a7R104-R123) , `FiberedWorker#run` returns not `[pid, Process::Status]`, but return s Array of this pairs.
> Fix FiberedWorker#run return value

- bintest/walkthrough.rb
The cleanup process is broken before #199, but test cannot notify this.
Add a new testcase to check cleanup, via pid file.
> Assert cleanup works

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/runner.rb
* Past: `hostname` of new UTS namespace should be forced to its `config.name`
* Now: `hostname` can be customizable if you specify `unshare "uts"`
> Add DSL for hostname spec

- mrblib/haconiwa/00_hookable.rb
- mrblib/haconiwa/runner.rb
Added `:immediately_after_fork_on_parent`. This is not for production hook, but useful to measure something in containers' bootup.
> Add a hook for performance monitoring or debug

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/criu_service.rb
Haconiwa uses action script internally. If more script needed, now wa can utilize!
https://criu.org/Action_scripts
> Add custom action script DSL entrypoint

- misc/hacoboot_sampler.bt
- sample/criu-rails.haco
This tool will get samples for elapsed time of:
* from time haconiwa is kicked to `execve` of the container begin
* from time haconiwa is kicked to `listen` and be ready
```console
$ sudo bpftrace misc/hacoboot_sampler.bt /u/app/helloworld/bin/rails                       
Attaching 5 probes...
^C
@execve__count: 3
@execve_avg: 70950886
@execve_max: 78633157
@execve_min: 59346736
@listen__count: 3
@listen_avg: 2240287035
@listen_max: 2359375184
@listen_min: 2100345924
```
> Add hacoboot_sampler tool

- mrbgem.rake
- mrblib/haconiwa/wait_loop.rb
Hi Ucchi!
I made `/proc/net/tcp` parser.
If this is used, the fork by system becomes unnecessary!
> Strictly check /proc/net/tcp by mruby-file-listen-checker

- mrblib/haconiwa/wait_loop.rb
Hi @udzura san ! 
I want to change to the same log level as [readiness_hooks`s ::Haconiwa::Logger](https://github.com/haconiwa/haconiwa/compare/master...k1LoW:change-async-hook-log-level?expand=1#diff-12348d78a22ff4eed4eb2ce6878d67e8R44)
Because this ::Haconiwa::Logger output every hook.interval ( if `interval_msec: 3000` , out every 3sec. )
> Change to the same log level as readiness_hooks`s ::Haconiwa::Logger

- mrbgem.rake
- mrblib/haconiwa/base.rb
Hi Ucchi!
I happend  `ip -f inet -o addr show brname` is very slow..
defenetaly ip command is throw NETLINK  command a lot. 
```
xxx.xxx # time ip -f inet -o addr show xxxxx
[snip]
real    0m3.385s
user    0m0.008s
sys     0m0.480s
root@staging-compute-1:/tmp# time ./a.out 
xx.xxx.xxx.xxx
real    0m0.002s
user    0m0.000s
sys     0m0.000s
```
then, i made mruby-ifaddr is more simply than ip command.
https://github.com/pyama86/mruby-ifaddr/blob/master/src/mrb_ifaddr.c#L45
we can boot up fast and fast !
> speed up acquisition of bridge ip

- mrblib/haconiwa/base.rb
- mrblib/haconiwa/wait_loop.rb
After https://github.com/udzura/mruby-fibered_worker/pull/12 is released, wa can handle worker's death by SIGCHLD handler. So just use blocking `sigtimedwait`, then we can reap children in real-time.
> Reduce CPU usage in busy waitloop

- mrblib/haconiwa/wait_loop.rb
- sample/criu.haco
Example log: 
```
Jan 28 07:32:40 ubuntu-bionic haconiwa.haconiwa-1580196760[21720]: Container fork success and going to wait: pid=21761      
Jan 28 07:32:40 ubuntu-bionic haconiwa.haconiwa-1580196760[21720]: Port 80 looks ready, yey!!! pid = 21761                  
Jan 28 07:32:40 ubuntu-bionic haconiwa.haconiwa-1580196760[21720]: Check hook stopped successfully                          
...
Jan 28 07:32:50 ubuntu-bionic haconiwa.haconiwa-1580196760[21720]: Hi! Tue Jan 28 07:32:50 UTC 2020#012 0                   
Jan 28 07:32:50 ubuntu-bionic haconiwa.haconiwa-1580196760[21720]: Hi! Tue Jan 28 07:32:50 UTC 2020#012 1                   
Jan 28 07:32:51 ubuntu-bionic haconiwa.haconiwa-1580196760[21720]: Hi! Tue Jan 28 07:32:51 UTC 2020#012 2                   
Jan 28 07:32:51 …
```
> Add loop count limit / Add accessor for current timewr in astnc loop

- mrblib/haconiwa/runner.rb
- mrblib/haconiwa/wait_loop.rb
Under the following condition, the container became a zombie process and Supervisor never terminate;
- Container process exit immediately
- Supervisor take a long time before do `waitloop.run_and_wait`
- e.g., `:immediately_after_fork_on_parent` hook took a long time.
It seems that the `CHLD` signal is ignored between forking the process and running the waitloop.
I think we can avoid this issue by running `sigprocmask` to block `CHLD` signal before forking, rather than when starting waitloop.
> block chld signal before fork

- mrblib/haconiwa/runner.rb
- src/haconiwa.c
I'm very sorry, I inserted bug on #228 ... :bow: :bow:
Container process could not be delivered `SIGCHLD` signal because signalmask is inherited from parent to child.
I wrote hot fix to this issue.
> [Hotfix] Fix that child process block SIGCHLD signal
